version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-examples-nodejs-customers-and-orders
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-tram-examples-nodejs-customers-and-orders-{{ checksum "end-to-end-tests/package.json" }}
            - eventuate-tram-examples-nodejs-customers-and-orders-
          paths:
            - ./end-to-end-tests/node_modules
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: eventuate-tram-examples-nodejs-customers-and-orders-{{ checksum "end-to-end-tests/package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-and-test
          command: |
            npm install
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all.sh
      - run:
          name: Save test results
          command: ./.circleci/save-containers-and-tests.sh
          when: always
      - store_artifacts:
          path: ~/container-logs
