version: 2
jobs:
  build:
    machine: true
    working_directory: ~/eventuate-tram-examples-nodejs-customers-and-orders
    steps:
      - checkout
      - restore_cache:
          keys:
            - eventuate-tram-examples-nodejs-customers-and-orders-{{ checksum "package.json" }}
            - eventuate-tram-examples-nodejs-customers-and-orders-
          paths:
            - ./node_modules
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: eventuate-tram-examples-nodejs-customers-and-orders-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install node@v12.16.1
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash
            . ./.circleci/load-nvm.sh
            nvm install v12.16.1
            nvm alias default v12.16.1
      - run:
          name: build-and-test
          command: |
            . ./.circleci/setenv-circle-ci.sh
            ./build-and-test-all.sh
      - run:
          name: Save test results
          command: ./.circle/save-containers-and-tests.sh
          when: always
      - store_artifacts:
          path: ~/container-logs
